apiVersion: apps/v1
kind: Deployment
metadata:
  name: skapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skapp1
  template:
    metadata:
      labels:
        app: skapp1
    spec:
      containers:
        - name: skapp1
          image: khatri27/sk-testmvc-aws:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: skapp1-service
spec:
  selector:
    app: skapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
  type: LoadBalancer